# -*- coding: utf-8 -*-
"""Aula_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGoi5crVngThbrubT0nZ5AHFWtk4UpgX
"""

import json
import pandas as pd
import plotly.express as px

file_path = 'datasheet.json'
with open(file_path, 'r') as file:
    data_json = json.load(file)

table_data = next(item for item in data_json if item['type'] == 'table')
data = table_data['data']
df = pd.DataFrame(data)

#display(df)

def convert_duration_to_minutes(duration):
    if 'min' in duration:
        return sum(int(x) * 60 ** i for i, x in enumerate(reversed(duration.replace(' min', '').split(','))))
    return int(duration)

df['Duração_min'] = df['Duração'].apply(convert_duration_to_minutes)
df['Tipo'] = df['Duração_min'].apply(lambda x: 'Filme' if x <= 120 else 'Série')

df_filmes = df[df['Tipo'] == 'Filme']
df_series = df[df['Tipo'] == 'Série']

def distruibuicao_por_genero(df, title):
    fig = px.bar(df, x='Genero', title=f'{title} - Distribuição por Gênero')
    return fig

def pontuacao_por_classificacao(df, title):
    fig = px.bar(df, x='Classificação', y='Pontuação', title=f'{title} - Média de Pontuação por Classificação')
    return fig

def votos_por_genero(df, title):
    fig = px.bar(df, x='Genero', y='Votos', title=f'{title} - Votos por Gênero')
    return fig

def duracao_classificacao(df, title):
    fig = px.bar(df, x='Classificação', y='Duração_min', title=f'{title} - Média de Duração por Classificação')
    return fig

distruibuicao_por_genero(df_filmes, 'Filmes')

pontuacao_por_classificacao(df_filmes, 'Filmes')

votos_por_genero(df_filmes, 'Filmes')

duracao_classificacao(df_filmes, 'Filmes')

distruibuicao_por_genero(df_series, 'Séries')

pontuacao_por_classificacao(df_series, 'Séries')

votos_por_genero(df_series, 'Séries')

duracao_classificacao(df_series, 'Séries')